#pragma once
#define QRX_DOMAIN_BLOCK "QRX_BLOCK"
#define QRX_DOMAIN_TX "QRX_TX"
#define QRX_DOMAIN_SNAPSHOT "QRX_SNAPSHOT"
#define QRX_DOMAIN_STATE "QRX_STATE"
#define QRX_DOMAIN_VALIDATOR "QRX_VALIDATOR"
