#pragma once
#define QRX_PROTOCOL_VERSION 2
#define QRX_TX_VERSION 2
#define QRX_VELOCITY_TX_VERSION 3
#define QRX_VELOCITY_FEATURE_LEVEL 6
#define QRX_BLOCK_VERSION 2
#define QRX_SNAPSHOT_VERSION 2
#define QRX_PROTOCOL_UPGRADE_HEIGHT 0
