#define _GNU_SOURCE
#include "storage/qrx_drive_runtime.h"
#include "storage/qrx_storage_network.h"
#include "storage/qrx_transfer_journal.h"
#include "storage/qrx_erasure.h"
#include "qrx_thread_compat.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <openssl/evp.h>
#include <sys/stat.h>
#ifdef _WIN32
#include <windows.h>
#include <direct.h>
#define SLEEP_MS(x) Sleep((DWORD)(x))
#define MKDIR_RT(p) _mkdir(p)
#else
#include <unistd.h>
#include <dirent.h>
#define SLEEP_MS(x) usleep((useconds_t)(x)*1000U)
#define MKDIR_RT(p) mkdir((p),0700)
#endif

typedef struct {char contract_id[129];QrxShardProviderSource s[QRX_DRIVE_RUNTIME_MAX_SOURCES];char pid[QRX_DRIVE_RUNTIME_MAX_SOURCES][129],ep[QRX_DRIVE_RUNTIME_MAX_SOURCES][256],oid[QRX_DRIVE_RUNTIME_MAX_SOURCES][65];size_t n;} SrcSet;
typedef struct Job {QrxDriveJobSnapshot v;pthread_t th;int thread_started;int pause,cancel;int prepared_upload;unsigned k,m;size_t shard_size;char source_path[1024];char prepared_shard_paths[QRX_DRIVE_PREPARE_MAX_SHARDS][1200];char prepared_oids[QRX_DRIVE_PREPARE_MAX_SHARDS][65];struct QrxDriveRuntime *rt;} Job;
struct QrxDriveRuntime {char chain_dir[1024],journal_dir[1024];pthread_mutex_t mu;Job jobs[QRX_DRIVE_RUNTIME_MAX_JOBS];SrcSet sources[QRX_DRIVE_RUNTIME_MAX_JOBS];size_t source_sets;uint64_t seq;int closing;};
static const char*state_name(QrxDriveJobState s){switch(s){case QRX_DRIVE_JOB_QUEUED:return"QUEUED";case QRX_DRIVE_JOB_RUNNING:return"RUNNING";case QRX_DRIVE_JOB_PAUSED:return"PAUSED";case QRX_DRIVE_JOB_COMPLETED:return"COMPLETED";case QRX_DRIVE_JOB_FAILED:return"FAILED";case QRX_DRIVE_JOB_CANCELLED:return"CANCELLED";default:return"EMPTY";}}
static void save_locked(Job*j){QrxTransferJournal x={0};snprintf(x.transfer_id,sizeof(x.transfer_id),"%s",j->v.transfer_id);snprintf(x.contract_id,sizeof(x.contract_id),"%s",j->v.contract_id);snprintf(x.direction,sizeof(x.direction),"%s",j->v.direction);snprintf(x.path,sizeof(x.path),"%s",j->v.path);x.total_bytes=j->v.total_bytes;x.completed_bytes=j->v.completed_bytes;x.completed_shards=j->v.completed_shards;x.required_shards=j->v.required_shards;x.data_shards=j->k;x.parity_shards=j->m;x.shard_size=j->shard_size;snprintf(x.state,sizeof(x.state),"%s",state_name(j->v.state));qrx_transfer_journal_save(j->rt->journal_dir,&x);}
static int wait_gate(Job*j){for(;;){pthread_mutex_lock(&j->rt->mu);int c=j->cancel, p=j->pause,closing=j->rt->closing;if(c||closing){j->v.state=QRX_DRIVE_JOB_CANCELLED;save_locked(j);pthread_mutex_unlock(&j->rt->mu);return -1;}if(!p){if(j->v.state==QRX_DRIVE_JOB_PAUSED)j->v.state=QRX_DRIVE_JOB_RUNNING;pthread_mutex_unlock(&j->rt->mu);return 0;}j->v.state=QRX_DRIVE_JOB_PAUSED;save_locked(j);pthread_mutex_unlock(&j->rt->mu);SLEEP_MS(30);}}
static SrcSet*srcset(QrxDriveRuntime*r,const char*c){for(size_t i=0;i<r->source_sets;i++)if(!strcmp(r->sources[i].contract_id,c))return&r->sources[i];return NULL;}
typedef struct{Job*j;QrxStorageNetworkFetchCtx net;const QrxShardProviderSource *sources;size_t source_count;} FetchCtx;
static int fetch_gate(void*v,const QrxShardProviderSource*s,const uint8_t id[64],uint64_t off,size_t len,uint8_t**out,size_t*outn){FetchCtx*c=v;if(wait_gate(c->j))return -1;int rc=qrx_storage_network_fetch_range(&c->net,s,id,off,len,out,outn);if(!rc){pthread_mutex_lock(&c->j->rt->mu);c->j->v.completed_bytes+=*outn;c->j->v.bytes_received+=*outn;save_locked(c->j);pthread_mutex_unlock(&c->j->rt->mu);}return rc;}
static int verify_oid(void*v,uint32_t si,const uint8_t*d,size_t n){FetchCtx*c=v;const char*want=NULL;for(size_t i=0;i<c->source_count;i++)if(c->sources[i].source.shard_index==si){want=c->sources[i].object_id_hex;break;}if(!want||strlen(want)!=64)return -1;unsigned char h[32];unsigned int hn=0;EVP_MD_CTX*m=EVP_MD_CTX_new();if(!m)return -1;int ok=EVP_DigestInit_ex(m,EVP_sha3_256(),NULL)==1&&EVP_DigestUpdate(m,d,n)==1&&EVP_DigestFinal_ex(m,h,&hn)==1&&hn==32;EVP_MD_CTX_free(m);if(!ok)return -1;static const char*x="0123456789abcdef";char got[65];for(int i=0;i<32;i++){got[i*2]=x[h[i]>>4];got[i*2+1]=x[h[i]&15];}got[64]=0;return strcmp(got,want)?-1:0;}
static int atomic_write(Job*j,const uint8_t*d,size_t n){char tmp[1200];if(snprintf(tmp,sizeof(tmp),"%s.qrxpart.%s",j->v.path,j->v.transfer_id)>=(int)sizeof(tmp))return -1;FILE*f=fopen(tmp,"wb");if(!f)return -1;size_t p=0;while(p<n){if(wait_gate(j)){fclose(f);remove(tmp);return -1;}size_t z=n-p;if(z>1024*1024)z=1024*1024;if(fwrite(d+p,1,z,f)!=z){fclose(f);remove(tmp);return -1;}p+=z;}if(fflush(f)||fclose(f)){remove(tmp);return -1;}if(rename(tmp,j->v.path)){remove(tmp);return -1;}return 0;}
static int source_file(const char*p,uint8_t**out,size_t*n){FILE*f=fopen(p,"rb");if(!f)return-1;if(fseek(f,0,SEEK_END)){fclose(f);return-1;}long z=ftell(f);if(z<0||fseek(f,0,SEEK_SET)){fclose(f);return-1;}uint8_t*b=malloc(z?((size_t)z):1);if(!b){fclose(f);return-1;}if(z&&fread(b,1,(size_t)z,f)!=(size_t)z){free(b);fclose(f);return-1;}fclose(f);*out=b;*n=(size_t)z;return 0;}
static int upload_one(Job*j,const QrxShardProviderSource*s,const uint8_t*d,size_t n){char p[1200];snprintf(p,sizeof(p),"%s/.qrx-upload-%s-%u.tmp",j->rt->journal_dir,j->v.transfer_id,s->source.shard_index);FILE*f=fopen(p,"wb");if(!f)return-1;int rc=(fwrite(d,1,n,f)==n&&fclose(f)==0)?qrx_storage_network_upload_file(s,j->v.contract_id,p):-1;remove(p);return rc;}
static void finish(Job*j,int rc,const char*err){pthread_mutex_lock(&j->rt->mu);if(j->cancel)j->v.state=QRX_DRIVE_JOB_CANCELLED;else if(!rc){j->v.state=QRX_DRIVE_JOB_COMPLETED;j->v.completed_bytes=j->v.total_bytes;j->v.completed_shards=j->v.total_shards;j->v.error[0]=0;}else{j->v.state=QRX_DRIVE_JOB_FAILED;snprintf(j->v.error,sizeof(j->v.error),"%s",err?err:"transfer failed");}save_locked(j);pthread_mutex_unlock(&j->rt->mu);}
static void*download_thread(void*v){Job*j=v;QrxDriveRuntime*r=j->rt;pthread_mutex_lock(&r->mu);SrcSet*ss=srcset(r,j->v.contract_id);if(!ss){pthread_mutex_unlock(&r->mu);finish(j,-1,"verified provider sources unavailable");return NULL;}QrxShardProviderSource local[32];size_t n=ss->n;memcpy(local,ss->s,n*sizeof(*local));j->v.state=QRX_DRIVE_JOB_RUNNING;save_locked(j);pthread_mutex_unlock(&r->mu);FetchCtx fc={j,{j->v.contract_id,5000,10000},local,n};QrxMultiFetchStats st={0};char tmp[1200];if(snprintf(tmp,sizeof(tmp),"%s.qrxpart.%s",j->v.path,j->v.transfer_id)>=(int)sizeof(tmp)){finish(j,-1,"target path too long");return NULL;}int rc=qrx_storage_stream_reconstruct_to_file(local,n,j->shard_size,j->k,j->m,(size_t)j->v.total_bytes,QRX_STORAGE_DEFAULT_FETCH_RANGE,fetch_gate,&fc,tmp,&st);pthread_mutex_lock(&r->mu);j->v.sources_started=(uint32_t)st.sources_started;j->v.sources_completed=(uint32_t)st.sources_completed;j->v.sources_failed=(uint32_t)st.sources_failed;j->v.hedges_started=(uint32_t)st.hedges_started;j->v.resumed_ranges=(uint32_t)st.resumed_ranges;j->v.cancelled_sources=(uint32_t)st.cancelled_sources;j->v.completed_shards=(uint32_t)st.successful_shards;pthread_mutex_unlock(&r->mu);if(!rc&&rename(tmp,j->v.path))rc=-1;if(rc)remove(tmp);finish(j,rc,rc?"streaming download/reconstruction failed":NULL);return NULL;}
static int upload_prepared_one(Job*j,const QrxShardProviderSource*s,uint32_t sh){if(sh>=j->k+j->m||!j->prepared_shard_paths[sh][0]||!j->prepared_oids[sh][0]||!s->object_id_hex||strcmp(s->object_id_hex,j->prepared_oids[sh]))return-1;return qrx_storage_network_upload_file(s,j->v.contract_id,j->prepared_shard_paths[sh]);}
static void*upload_thread(void*v){Job*j=v;QrxDriveRuntime*r=j->rt;pthread_mutex_lock(&r->mu);SrcSet*ss=srcset(r,j->v.contract_id);if(!ss){pthread_mutex_unlock(&r->mu);finish(j,-1,"verified provider sources unavailable");return NULL;}QrxShardProviderSource local[32];size_t n=ss->n;memcpy(local,ss->s,n*sizeof(*local));j->v.state=QRX_DRIVE_JOB_RUNNING;save_locked(j);pthread_mutex_unlock(&r->mu);QrxErasureSet es={0};if(!j->prepared_upload){uint8_t*d=NULL;size_t dn=0;if(source_file(j->source_path,&d,&dn)){finish(j,-1,"source file unavailable");return NULL;}if(qrx_erasure_encode(d,dn,j->k,j->m,&es)){free(d);finish(j,-1,"erasure encode failed");return NULL;}free(d);}int rc=0;uint32_t ok=0;for(size_t i=0;i<n;i++){if(wait_gate(j)){rc=-1;break;}uint32_t sh=local[i].source.shard_index;int urc=j->prepared_upload?upload_prepared_one(j,&local[i],sh):(sh>=j->k+j->m||upload_one(j,&local[i],es.shards[sh],es.shard_size));if(urc){rc=-1;continue;}ok++;pthread_mutex_lock(&r->mu);j->v.completed_shards=ok;j->v.completed_bytes=(uint64_t)ok*j->shard_size;if(j->v.completed_bytes>j->v.total_bytes)j->v.completed_bytes=j->v.total_bytes;save_locked(j);pthread_mutex_unlock(&r->mu);}if(!j->prepared_upload)qrx_erasure_free(&es);if(ok<j->v.required_shards)rc=-1;finish(j,rc,rc?"insufficient uploaded shards":NULL);return NULL;}
int qrx_drive_runtime_open(const char*c,const char*j,QrxDriveRuntime**out){if(!c||!j||!out)return-1;QrxDriveRuntime*r=calloc(1,sizeof(*r));if(!r)return-1;snprintf(r->chain_dir,sizeof(r->chain_dir),"%s",c);snprintf(r->journal_dir,sizeof(r->journal_dir),"%s",j);MKDIR_RT(j);pthread_mutex_init(&r->mu,NULL);r->seq=(uint64_t)time(NULL)*1000ULL;
#ifndef _WIN32
DIR*d=opendir(j);if(d){struct dirent*de;while((de=readdir(d))){size_t ln=strlen(de->d_name);if(ln<9||strcmp(de->d_name+ln-8,".journal"))continue;char id[129];size_t il=ln-8;if(il>=sizeof(id))continue;memcpy(id,de->d_name,il);id[il]=0;QrxTransferJournal q;if(qrx_transfer_journal_load(j,id,&q))continue;if(!strcmp(q.state,"COMPLETED")||!strcmp(q.state,"FAILED")||!strcmp(q.state,"CANCELLED"))continue;for(size_t i=0;i<QRX_DRIVE_RUNTIME_MAX_JOBS;i++)if(r->jobs[i].v.state==QRX_DRIVE_JOB_EMPTY){Job*z=&r->jobs[i];memset(z,0,sizeof(*z));z->rt=r;snprintf(z->v.transfer_id,sizeof(z->v.transfer_id),"%s",q.transfer_id);snprintf(z->v.contract_id,sizeof(z->v.contract_id),"%s",q.contract_id);snprintf(z->v.direction,sizeof(z->v.direction),"%s",q.direction);snprintf(z->v.path,sizeof(z->v.path),"%s",q.path);snprintf(z->source_path,sizeof(z->source_path),"%s",q.path);z->v.total_bytes=q.total_bytes;z->v.completed_bytes=q.completed_bytes;z->v.completed_shards=q.completed_shards;z->v.required_shards=q.required_shards;z->k=q.data_shards?q.data_shards:q.required_shards;z->m=q.parity_shards?q.parity_shards:4;z->shard_size=(size_t)(q.shard_size?q.shard_size:((q.total_bytes+z->k-1)/z->k));z->v.total_shards=z->k+z->m;z->v.state=QRX_DRIVE_JOB_PAUSED;snprintf(z->v.error,sizeof(z->v.error),"Recovered after daemon restart; resume requires verified provider discovery.");break;}}closedir(d);}
#endif
*out=r;return 0;}
void qrx_drive_runtime_close(QrxDriveRuntime*r){if(!r)return;pthread_mutex_lock(&r->mu);r->closing=1;for(size_t i=0;i<QRX_DRIVE_RUNTIME_MAX_JOBS;i++)if(r->jobs[i].thread_started)r->jobs[i].cancel=1;pthread_mutex_unlock(&r->mu);for(size_t i=0;i<QRX_DRIVE_RUNTIME_MAX_JOBS;i++)if(r->jobs[i].thread_started)pthread_join(r->jobs[i].th,NULL);pthread_mutex_destroy(&r->mu);free(r);}
int qrx_drive_runtime_set_contract_sources(QrxDriveRuntime*r,const char*c,const QrxShardProviderSource*s,size_t n){if(!r||!c||!*c||!s||!n||n>32)return-1;pthread_mutex_lock(&r->mu);SrcSet*x=srcset(r,c);if(!x){if(r->source_sets>=QRX_DRIVE_RUNTIME_MAX_JOBS){pthread_mutex_unlock(&r->mu);return-1;}x=&r->sources[r->source_sets++];memset(x,0,sizeof(*x));snprintf(x->contract_id,sizeof(x->contract_id),"%s",c);}x->n=n;for(size_t i=0;i<n;i++){snprintf(x->pid[i],sizeof(x->pid[i]),"%s",s[i].provider_id?s[i].provider_id:"");snprintf(x->ep[i],sizeof(x->ep[i]),"%s",s[i].endpoint?s[i].endpoint:"");snprintf(x->oid[i],sizeof(x->oid[i]),"%s",s[i].object_id_hex?s[i].object_id_hex:"");x->s[i]=s[i];x->s[i].provider_id=x->pid[i];x->s[i].endpoint=x->ep[i];x->s[i].object_id_hex=x->oid[i];}pthread_mutex_unlock(&r->mu);return 0;}
static Job*newjob(QrxDriveRuntime*r,const char*c,const char*dir,const char*p,uint64_t total,unsigned k,unsigned m,char id[129]){for(size_t i=0;i<64;i++)if(r->jobs[i].v.state==QRX_DRIVE_JOB_EMPTY){Job*j=&r->jobs[i];memset(j,0,sizeof(*j));j->rt=r;j->k=k;j->m=m;snprintf(j->v.transfer_id,sizeof(j->v.transfer_id),"drv-%llu-%llu",(unsigned long long)time(NULL),(unsigned long long)++r->seq);snprintf(j->v.contract_id,sizeof(j->v.contract_id),"%s",c);snprintf(j->v.direction,sizeof(j->v.direction),"%s",dir);snprintf(j->v.path,sizeof(j->v.path),"%s",p);j->v.total_bytes=total;j->v.required_shards=k;j->v.total_shards=k+m;j->v.state=QRX_DRIVE_JOB_QUEUED;snprintf(id,129,"%s",j->v.transfer_id);save_locked(j);return j;}return NULL;}
int qrx_drive_runtime_start_download(QrxDriveRuntime*r,const char*c,const char*p,uint64_t original,size_t shard,unsigned k,unsigned m,char id[129]){if(!r||!c||!p||!id||!original||!shard||!k||!m)return-1;pthread_mutex_lock(&r->mu);if(!srcset(r,c)){pthread_mutex_unlock(&r->mu);return-2;}Job*j=newjob(r,c,"download",p,original,k,m,id);if(j)j->shard_size=shard;if(!j||pthread_create(&j->th,NULL,download_thread,j)){if(j)j->v.state=QRX_DRIVE_JOB_FAILED;pthread_mutex_unlock(&r->mu);return-1;}j->thread_started=1;pthread_mutex_unlock(&r->mu);return 0;}
int qrx_drive_runtime_start_upload(QrxDriveRuntime*r,const char*c,const char*p,unsigned k,unsigned m,char id[129]){if(!r||!c||!p||!id||!k||!m)return-1;struct stat st;if(stat(p,&st)||st.st_size<0)return-1;pthread_mutex_lock(&r->mu);if(!srcset(r,c)){pthread_mutex_unlock(&r->mu);return-2;}Job*j=newjob(r,c,"upload",p,(uint64_t)st.st_size,k,m,id);if(j)snprintf(j->source_path,sizeof(j->source_path),"%s",p);if(!j||pthread_create(&j->th,NULL,upload_thread,j)){if(j)j->v.state=QRX_DRIVE_JOB_FAILED;pthread_mutex_unlock(&r->mu);return-1;}j->thread_started=1;pthread_mutex_unlock(&r->mu);return 0;}
static int start_signed_prepared(QrxDriveRuntime*r,const char*c,const QrxDrivePreparedUpload*p,const char*suite,const char*direction,char id[129]){if(!r||!c||!p||!id||strcmp(p->manifest.crypto_suite,suite)||p->total_shards!=p->data_shards+p->parity_shards||qrx_drive_prepared_upload_verify_files(p))return-1;pthread_mutex_lock(&r->mu);SrcSet*ss=srcset(r,c);if(!ss){pthread_mutex_unlock(&r->mu);return-2;}if(qrx_drive_prepared_upload_verify_sources(p,ss->s,ss->n)){pthread_mutex_unlock(&r->mu);return-3;}Job*j=newjob(r,c,direction,p->package_dir,p->ciphertext_bytes,p->data_shards,p->parity_shards,id);if(j){j->prepared_upload=1;j->shard_size=(size_t)p->shard_bytes;for(unsigned i=0;i<p->total_shards;i++){snprintf(j->prepared_shard_paths[i],sizeof(j->prepared_shard_paths[i]),"%s",p->shard_paths[i]);snprintf(j->prepared_oids[i],sizeof(j->prepared_oids[i]),"%s",p->shard_object_ids[i]);}}if(!j||pthread_create(&j->th,NULL,upload_thread,j)){if(j)j->v.state=QRX_DRIVE_JOB_FAILED;pthread_mutex_unlock(&r->mu);return-1;}j->thread_started=1;pthread_mutex_unlock(&r->mu);return 0;}
int qrx_drive_runtime_start_prepared_upload(QrxDriveRuntime*r,const char*c,const QrxDrivePreparedUpload*p,char id[129]){return start_signed_prepared(r,c,p,QRX_DRIVE_SUITE_PRIVATE_PQ,"upload-private-pq",id);}
int qrx_drive_runtime_start_public_signed_upload(QrxDriveRuntime*r,const char*c,const QrxDrivePreparedUpload*p,char id[129]){return start_signed_prepared(r,c,p,QRX_DRIVE_SUITE_PUBLIC_SIGNED,"upload-public-signed",id);}
static Job*findjob(QrxDriveRuntime*r,const char*id){for(size_t i=0;i<64;i++)if(r->jobs[i].v.state&& !strcmp(r->jobs[i].v.transfer_id,id))return&r->jobs[i];return NULL;}
int qrx_drive_runtime_pause(QrxDriveRuntime*r,const char*id){pthread_mutex_lock(&r->mu);Job*j=findjob(r,id);if(!j||j->v.state>=QRX_DRIVE_JOB_COMPLETED){pthread_mutex_unlock(&r->mu);return-1;}j->pause=1;j->v.state=QRX_DRIVE_JOB_PAUSED;save_locked(j);pthread_mutex_unlock(&r->mu);return 0;}
int qrx_drive_runtime_resume(QrxDriveRuntime*r,const char*id){pthread_mutex_lock(&r->mu);Job*j=findjob(r,id);if(!j||j->v.state>=QRX_DRIVE_JOB_COMPLETED){pthread_mutex_unlock(&r->mu);return-1;}if(!j->thread_started){if(!srcset(r,j->v.contract_id)){pthread_mutex_unlock(&r->mu);return-2;}j->pause=0;j->v.state=QRX_DRIVE_JOB_QUEUED;void*(*fn)(void*)=!strncmp(j->v.direction,"upload",6)?upload_thread:download_thread;if(pthread_create(&j->th,NULL,fn,j)){j->v.state=QRX_DRIVE_JOB_FAILED;pthread_mutex_unlock(&r->mu);return-1;}j->thread_started=1;}else{j->pause=0;j->v.state=QRX_DRIVE_JOB_RUNNING;}j->v.error[0]=0;save_locked(j);pthread_mutex_unlock(&r->mu);return 0;}
int qrx_drive_runtime_cancel(QrxDriveRuntime*r,const char*id){pthread_mutex_lock(&r->mu);Job*j=findjob(r,id);if(!j||j->v.state>=QRX_DRIVE_JOB_COMPLETED){pthread_mutex_unlock(&r->mu);return-1;}j->cancel=1;j->v.state=QRX_DRIVE_JOB_CANCELLED;save_locked(j);pthread_mutex_unlock(&r->mu);return 0;}
int qrx_drive_runtime_get(QrxDriveRuntime*r,const char*id,QrxDriveJobSnapshot*out){if(!r||!id||!out)return-1;pthread_mutex_lock(&r->mu);Job*j=findjob(r,id);if(!j){pthread_mutex_unlock(&r->mu);return-1;}*out=j->v;pthread_mutex_unlock(&r->mu);return 0;}
size_t qrx_drive_runtime_list(QrxDriveRuntime*r,QrxDriveJobSnapshot*out,size_t cap){if(!r)return 0;pthread_mutex_lock(&r->mu);size_t n=0;for(size_t i=0;i<64;i++)if(r->jobs[i].v.state){if(out&&n<cap)out[n]=r->jobs[i].v;n++;}pthread_mutex_unlock(&r->mu);return n;}
